name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install || echo "Retrying npm install..."

          # Ensure @react-three/drei installation
          if ! npm list @react-three/drei >/dev/null 2>&1; then
            echo "@react-three/drei missing. Installing..."
            npm install @react-three/drei || exit 1
          fi

          # Ensure Next.js installation
          if ! npm list next >/dev/null 2>&1; then
            echo "Next.js missing, installing manually..."
            npm install next || exit 1
          fi

          # Update TypeScript, React, and React DOM
          echo "Ensuring compatible TypeScript and React versions..."
          npm install typescript@latest react@latest react-dom@latest

          # Debug dependency tree
          echo "Debugging final dependency tree..."
          npm ls
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Validate environment variables
        run: |
          if [ -z "${NEXT_PUBLIC_SUPABASE_URL}" ] || [ -z "${NEXT_PUBLIC_SUPABASE_ANON_KEY}" ]; then
            echo "Environment variables are missing!"
            exit 1
          fi

      - name: Configure ESLint for Next.js
        run: |
          echo "Installing and configuring ESLint for Next.js..."
          npm install eslint-plugin-next --legacy-peer-deps --save-dev
          echo '{
            "extends": ["next/core-web-vitals"]
          }' > .eslintrc.json

      - name: Clear cached build files
        run: |
          echo "Clearing cached build files..."
          rm -rf .next

      - name: Build the application
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_KEY }}
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "Deploying to Vercel..."
          npx vercel --prod --yes --token=$VERCEL_TOKEN
