name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 0 * * *" # Run the workflow daily at midnight (UTC)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out the code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Set environment variables
      - name: Set Pexels API Key
        run: echo "PEXELS_API_KEY=${{ secrets.PEXELS_API_KEY }}" >> $GITHUB_ENV

      # Step 5: Preload Background Images
      # This script preloads images for better performance and caching.
      - name: Preload Background Images
        run: node ./scripts/preloadImages.js

      # Step 6: Run Utility Scripts (if applicable)
      # Add other utility scripts that need execution
      - name: Run Utility Scripts
        run: node ./scripts/utilityScripts.js

      # Step 7: Generate CSS with Tailwind
      - name: Generate CSS with Tailwind
        run: |
          mkdir -p ./styles
          echo -e "@tailwind base;\n@tailwind components;\n@tailwind utilities;" > ./styles/input.css
          npx tailwindcss -i ./styles/input.css -o ./styles/output.css --minify

      # Step 8: Build the project
      - name: Build the project
        run: npm run build

      # Step 9: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: "codewithwill.tech" # Replace with your custom domain if applicable

  # Periodic Background Preloading Job
  preload-backgrounds:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Set Pexels API Key
        run: echo "PEXELS_API_KEY=${{ secrets.PEXELS_API_KEY }}" >> $GITHUB_ENV

      - name: Preload Background Images
        run: node ./scripts/preloadImages.js

      - name: Commit and Push Preloaded Images
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add public/preloaded-images/
          git commit -m "Update preloaded images [skip ci]" || echo "No changes to commit"
          git push