name: Deploy Application with Supabase Initialization

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps
          npm install eslint-plugin-next @supabase/supabase-js three@^0.171.0 googleapis @sendgrid/mail pino stripe --legacy-peer-deps
          npm install eslint-plugin-next @types/stripe --save-dev
          npm install --package-lock-only
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Debug Supabase Client Usage
        run: |
          echo "Checking Supabase client initialization..."
          grep -r "createClient" ./src || echo "No Supabase client initialization found."
          grep -r "supabase" ./src || echo "Supabase usage not found."

      - name: Debug R3F Hook Usage
        run: |
          echo "Searching for R3F hooks..."
          grep -r "useFrame" ./src || echo "No R3F hooks found."
          grep -r "Canvas" ./src || echo "No Canvas usage found."

      - name: Build the Application
        run: npm run build || echo "Build failed"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Upload Debug Logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: debug-logs
          path: $GITHUB_WORKSPACE/debug.log