name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm ci
          npm install @tailwindcss/forms @tailwindcss/typography react-circular-progressbar

      # Step 4: Generate CSS with Tailwind
      - name: Generate CSS with Tailwind
        run: |
          mkdir -p ./styles
          echo -e "@tailwind base;\n@tailwind components;\n@tailwind utilities;" > ./styles/input.css
          npx tailwindcss -i ./styles/input.css -o ./styles/output.css --minify

      # Step 5: Copy Fonts and Assets
      - name: Copy Fonts and Assets
        run: |
          mkdir -p ./public/fonts
          cp -r ./assets/fonts/* ./public/fonts/ || echo "No fonts to copy"
          mkdir -p ./public/backgrounds
          cp -r ./assets/backgrounds/* ./public/backgrounds/ || echo "No backgrounds to copy"
          mkdir -p ./public/icons
          cp -r ./assets/icons/* ./public/icons/ || echo "No icons to copy"

      # Step 6: Build the project
      - name: Build the project
        run: npm run build

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: "codewithwill.tech" # Replace with your custom domain if needed