name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache Node.js modules
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_KEY }}

      # Validate Environment Variables
      - name: Validate environment variables
        run: |
          if [ -z "${NEXT_PUBLIC_SUPABASE_URL}" ] || [ -z "${NEXT_PUBLIC_SUPABASE_ANON_KEY}" ]; then
            echo "Environment variables are missing!"
            exit 1
          fi
          echo "All required environment variables are set."

      # Lint and Type-Check Code
      - name: Lint and Type-Check
        run: |
          npm run lint || true
          npm run type-check
        env:
          CI: true

      # Pre-Build Debugging
      - name: Debug Dependency Tree
        run: |
          npm ls --all

      # Advanced Debugging for Missing Modules
      - name: Check Missing Modules
        run: |
          node -e "require('./components/UI/Modal.tsx')"

      # Build the application
      - name: Build the application
        env:
          CI: false
        run: npm run build
        continue-on-error: true

      # Advanced Debugging for Build Errors
      - name: Collect Build Logs
        if: failure()
        run: |
          echo "=== Build Failed Logs ==="
          cat .next/cache/failed-build.log || echo "No logs found"

      # Deploy to Vercel
      - name: Deploy to Vercel
        run: |
          npx vercel --prod --yes --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_KEY }}