name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm install eslint-plugin-next @supabase/supabase-js --legacy-peer-deps
          npm install --package-lock-only

      # Step 4: Commit lockfile if updated
      - name: Commit Updated Lockfile
        if: always()
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add package-lock.json
          git commit -m "Update package-lock.json [ci skip]" || echo "No changes to commit"
          git push origin main || echo "No changes pushed"

      # Step 5: TypeScript compilation
      - name: Debug TypeScript Compilation
        run: tsc --noEmit || echo "TypeScript compilation failed"

      # Step 6: Lint code
      - name: Lint Code
        run: npm run lint || echo "Lint warnings detected"

      # Step 7: Build the application
      - name: Build Application
        run: |
          npm run build || echo "Build failed"

      # Step 8: Deploy to Vercel
      - name: Deploy to Vercel
        run: |
          npx vercel --prod --yes --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}