name: Deploy Application with Supabase Initialization

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Reorganize directories
      - name: Move lib directory to src/lib
        run: |
          mkdir -p src
          mv lib src/lib || echo "lib directory already moved"
          mv src/lib/googleCalender.ts src/lib/googleCalendar.ts || echo "File already renamed"

      # Verify directory structure
      - name: Verify Directory Structure
        run: |
          ls -R src || echo "src directory not found"
          ls -R src/lib || echo "src/lib directory not found"

      # Commit directory changes
      - name: Commit src/lib changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Move lib to src/lib and rename files" || echo "No changes to commit"

      # Clear npm cache
      - name: Clear npm cache
        run: npm cache clean --force

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      # Install Dependencies

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps
          npm install eslint-plugin-next @supabase/supabase-js three@^0.172.0 googleapis@^144.0.0 @sendgrid/mail pino stripe react-circular-progressbar autoprefixer tailwindcss @tailwindcss/forms @tailwindcss/typography @tailwindcss/aspect-ratio --legacy-peer-deps
          npm install flatpickr react-flatpickr --legacy-peer-deps
          npm install eslint-plugin-next @typescript-eslint/eslint-plugin@^6.21.0 eslint@^8.57.1 postcss@^8.4.24 --save-dev --legacy-peer-deps
          npm install --package-lock-only --legacy-peer-deps
        env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      - name: Install react-modern-calendar-datepicker
        run: npm install react-modern-calendar-datepicker --legacy-peer-deps

      # Verify installed dependencies
      - name: Verify Installed Node Modules
        run: |
          ls node_modules || echo "node_modules directory not found"
          npm list stripe || echo "Stripe is not installed correctly"
          npm list autoprefixer || echo "Autoprefixer is not installed correctly"
          npm list react-circular-progressbar || echo "react-circular-progressbar is not installed correctly"

      # Fix TypeScript imports
      - name: Fix TypeScript Imports and Paths
        run: |
          find ./pages ./utils ./components ./scripts ./styles ./public ./src -type f -name "*.ts*" -exec sed -i 's|@/lib|@/src/lib|g' {} +
          grep -r "supabase" ./src || echo "Supabase usage not found."

      # Add missing TypeScript declarations
      - name: Add Missing TypeScript Declarations
        run: |
          echo 'declare module "react-circular-progressbar";' >> react-circular-progressbar.d.ts

      # Lint the code
      - name: Lint Code
        run: npm run lint || echo "Lint warnings detected"

      # Build the application
      - name: Build Application
        run: npm run build || echo "Build failed"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_KEY }}

      # Deploy to Vercel
      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}