name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Only deploy when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Lint the code
        run: npm run lint

      - name: Build the application
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Add this token in GitHub Secrets
        run: npx vercel --prod --token=$VERCEL_TOKEN
